### ISSUE TITLE
Gleam buttons go ontop of message

### ISSUE THREAD

**Issue by nihaals** [Citrinate/giveawayHelper#38]
![image](https://user-images.githubusercontent.com/18350092/34977839-0d9f92ca-fa94-11e7-891e-0df8d4b571f5.png)

**Comment by Citrinate** [comment]
I don't think it's something I'll be fixing.

If I allowed the message to appear over the button, it would be hard to click the button while the message was up.  I also can't place the button to the right of the checkbox because there's no room for it when a Gleam.io giveaway is embedded ([example](https://gleam.io/docs/installation/add-page)).

It's not ideal, but considering that the text is just a description of the "+1" or the "✔" icon, which themselves are clear enough without it, I don't feel that much is being lost by blocking it.
